<?php
$productosss = [
    [
        "id" => 1,
        "categoria" => "trending",
        "nombre" => "POLLERA CORD MARGO",
        "prenda" => "Pollera",
        "color" => "Rosa",
        "talle" => 38,
        "descripcion" => "Las polleras con cruce asimétrico son una tendencia que no puede faltar en tu placard. La pollera Margo es de corderoy de algodón. Tiene cinco bolsillos y cuenta con cuatro botones metálicos. ¡Podés agregarle un cinturón!",
        "imagen" => "img/productos/pollera-margo.webp",
        "precio" => 19590,
        "publicacion" => "Marzo 2023",
    ],
    [
        "id" => 2,
        "categoria" => "trending",
        "nombre" => "REMERA FLORA",
        "prenda" => "Remera",
        "color" => "Blanco",
        "talle" => 42,
        "descripcion" => "La remera Flora es de jersey de algodón con elastano. Tiene mangas largas y frente cruzado, con escote. ¡Nos encantan sus tiras para ajustar! Súper cancheras y a la moda.",
        "imagen" => "img/productos/remera-flora.webp",
        "precio" => 10300,
        "publicacion" => "Febrero 2023",
    ],
    [
        "id" => 3,
        "categoria" => "verano-2023",
        "nombre" => "CHALECO ARENA",
        "prenda" => "Chaleco",
        "color" => "Beige",
        "talle" => 3,
        "descripcion" => "El chaleco Arena es de gabardina de algodón. Es tipo sastrero, una tendencia que no puede faltarte esta temporada. Cuenta con cuatro botones, para ajustar como vos más quieras.",
        "imagen" => "img/productos/chaleco-arena.webp",
        "precio" => 15450,
        "publicacion" => "Febrero 2023",
    ],
    [
        "id" => 4,
        "categoria" => "verano-2023",
        "nombre" => "MUSCULOSA DANNA",
        "prenda" => "Musculosa",
        "color" => "Negro",
        "talle" => 36,
        "descripcion" => "La musculosa Danna es de morley de algodón con elastano. Tiene breteles anchos. Este básico es un must para combinar con cualquier denim, ¡para ser la teen más canchera!",
        "imagen" => "img/productos/musculosa-danna.webp",
        "precio" => 6180,
        "publicacion" => "Enero 2023",
    ],
    [
        "id" => 5,
        "categoria" => "invierno-2023",
        "nombre" => "CAMPERA BOSTON",
        "prenda" => "Campera",
        "color" => "Celeste",
        "talle" => 34,
        "descripcion" => "La campera Boston es una opción colorida y súper abrigada para los días más fríos. Es de poliamida, con efecto engomado, forrada en tafeta con relleno de vellón siliconado. Tiene el cuello alto y con botones, para mantenerte protegida del viento.",
        "imagen" => "img/productos/campera-boston.webp",
        "precio" => 39000,
        "publicacion" => "Junio 2023",
    ],
    [
        "id" => 6,
        "categoria" => "invierno-2023",
        "nombre" => "CAMPERA ACADEMY",
        "prenda" => "Campera",
        "color" => "Beige",
        "talle" => 32,
        "descripcion" => "La campera Academy combina tendencias, funcionalidad y abrigo. Es de microfibra de poliéster, forrada en tafeta y rellena con vellón siliconado. Tiene capucha, cierre, cordones de satén y bolsillos. ¡Sí, lo tiene todo!",
        "imagen" => "img/productos/campera-academy.webp",
        "precio" => 41150,
        "publicacion" => "Junio 2023",
    ],
];

echo json_encode($productosss);