<?php
$productosss = [
    [
        "id" => 1,
        "categoria" => "trending",
        "nombre" => "POLLERA CORD MARGO",
        "prenda" => "Pollera",
        "color" => "Rosa",
        "talle" => 38,
        "descripcion" => "Las polleras con cruce asimétrico son una tendencia que no puede faltar en tu placard. La pollera Margo es de corderoy de algodón. Tiene cinco bolsillos y cuenta con cuatro botones metálicos. ¡Podés agregarle un cinturón!",
        "imagen" => "img/productos/pollera-margo.webp",
        "precio" => 19590,
        "publicacion" => "Marzo, 2023",
    ],
    [
        "id" => 2,
        "categoria" => "trending",
        "nombre" => "REMERA FLORA",
        "prenda" => "Remera",
        "color" => "Blanco",
        "talle" => 42,
        "descripcion" => "La remera Flora es de jersey de algodón con elastano. Tiene mangas largas y frente cruzado, con escote. ¡Nos encantan sus tiras para ajustar! Súper cancheras y a la moda.",
        "imagen" => "img/productos/remera-flora.webp",
        "precio" => 10300,
        "publicacion" => "Febrero, 2023",
    ],
    [
        "id" => 3,
        "categoria" => "verano-2023",
        "nombre" => "CHALECO ARENA",
        "prenda" => "Chaleco",
        "color" => "Beige",
        "talle" => 3,
        "descripcion" => "El chaleco Arena es de gabardina de algodón. Es tipo sastrero, una tendencia que no puede faltarte esta temporada. Cuenta con cuatro botones, para ajustar como vos más quieras.",
        "imagen" => "img/productos/chaleco-arena.webp",
        "precio" => 15450,
        "publicacion" => "Febrero, 2023",
    ],
    [
        "id" => 4,
        "categoria" => "verano-2023",
        "nombre" => "MUSCULOSA DANNA",
        "prenda" => "Musculosa",
        "color" => "Negro",
        "talle" => 36,
        "descripcion" => "La musculosa Danna es de morley de algodón con elastano. Tiene breteles anchos. Este básico es un must para combinar con cualquier denim, ¡para ser la teen más canchera!",
        "imagen" => "img/productos/musculosa-danna.webp",
        "precio" => 6180,
        "publicacion" => "Enero, 2023",
    ],
    [
        "id" => 5,
        "categoria" => "invierno-2023",
        "nombre" => "CAMPERA BOSTON",
        "prenda" => "Campera",
        "color" => "Celeste",
        "talle" => 34,
        "descripcion" => "La campera Boston es una opción colorida y súper abrigada para los días más fríos. Es de poliamida, con efecto engomado, forrada en tafeta con relleno de vellón siliconado. Tiene el cuello alto y con botones, para mantenerte protegida del viento.",
        "imagen" => "img/productos/campera-boston.webp",
        "precio" => 39000,
        "publicacion" => "Junio, 2023",
    ],
    [
        "id" => 6,
        "categoria" => "invierno-2023",
        "nombre" => "CAMPERA ACADEMY",
        "prenda" => "Campera",
        "color" => "Beige",
        "talle" => 32,
        "descripcion" => "La campera Academy combina tendencias, funcionalidad y abrigo. Es de microfibra de poliéster, forrada en tafeta y rellena con vellón siliconado. Tiene capucha, cierre, cordones de satén y bolsillos. ¡Sí, lo tiene todo!",
        "imagen" => "img/productos/campera-academy.webp",
        "precio" => 41150,
        "publicacion" => "Junio, 2023",
    ],
    [
        "id"=> 7,
        "categoria"=> "invierno-2023",
        "nombre"=> "CAMPERA SKYLER",
        "prenda"=> "Campera",
        "color"=>"Lila",
        "talle"=> 38,
        "descripcion"=> "La campera Skyler es una opción súper calentita para los días más fríos. Es de poliamida, con efecto engomado, forrada en tafeta con relleno de vellón siliconado. ¡Su color y estilo representan totalmente a Lilac!",
        "imagen"=> "img/productos/campera-skyler.webp",
        "precio"=> 27230,
        "publicacion"=> "Agosto, 2023"
    ],
    [
        "id"=> 8,
        "categoria"=> "invierno-2023",
        "nombre"=> "REMERA DUA",
        "prenda"=> "Remera",
        "color"=>"Negro",
        "talle"=> 32,
        "descripcion"=> "La remera Dua es de jersey de algodón con elastano. Tiene mangas largas con abertura para dedo pulgar, y cuello redondo. Cuenta con un aplique de strass en forma de mariposa en delantero, que la hace súper canchera y le da toda la onda. Está disponible en color negro, con costuras hacia afuera a contratono en blanco. ¡Te invitamos a que te animes a usarla en tus looks invernales!",
        "imagen"=> "img/productos/remera-dua.webp",
        "precio"=> 8160,
        "publicacion"=> "Agosto, 2023"
    ],
    [
        "id"=> 9,
        "categoria"=> "invierno-2023",
        "nombre"=> "BUZO LULI",
        "prenda"=> "Buzo",
        "color"=>"Beige",
        "talle"=> 34,
        "descripcion"=> "El buzo Luli es de corderoy de punto, de algodón con poliéster. Tiene capucha forrada y cierre. Además, cuenta con elásticos en puños y cintura. Es una opción abrigada y cómoda para esta temporada de invierno. Para las amantes de los tonos neutro, ¡está disponible en beige!",
        "imagen"=> "img/productos/buzo-luli.webp",
        "precio"=> 12530,
        "publicacion"=> "Julio, 2023"
    ],
    [
        "id"=> 10,
        "categoria"=> "invierno-2023",
        "nombre"=> "SWEATER MATCH",
        "prenda"=> "Sweater",
        "color"=>"Verde",
        "talle"=> 3,
        "descripcion"=> "¿Te gusta el estilo polo? Este sweater es para vos. El sweater polo Match es tejido, con hilado mezcla de algodón y acrílico. Tiene cuello tipo camionero, y cierre metálico. Está disponible en color verde oscuro. ¡Es el combo perfecto entre abrigo y color!",
        "imagen"=> "img/productos/sweater-match.webp",
        "precio"=> 13330,
        "publicacion"=> "Junio, 2023"
    ],
    [
        "id"=> 11,
        "categoria"=> "invierno-2023",
        "nombre"=> "BUZO LILAC",
        "prenda"=> "Buzo",
        "color"=>"Lila",
        "talle"=> 36,
        "descripcion"=> "El buzo Lilac es de frisa de algodón con poliéster. Tiene el cuello redondo, con recortes. El frente es más corto que la espalda. Está disponible en color lila, con una estampa en la espalda. ¡Su color y estilo representan totalmente a Lilac!",
        "imagen"=> "img/productos/buzo-lilac.webp",
        "precio"=> 11900,
        "publicacion"=> "Junio, 2023"
    ],
    [
        "id"=> 12,
        "categoria"=> "invierno-2023",
        "nombre"=> "BUZO COMFORT",
        "prenda"=> "Buzo",
        "color"=>"Marrón",
        "talle"=> 42,
        "descripcion"=> "Una opción suelta, canchera y cómoda para tu look. El buzo Comfort es de frisa de algodón con poliéster. Tiene cuello redondo, con puños y cintura en ribb. Es de color marrón, con estampa en el frente y la espalda. Para usarlo en los días más confortables.",
        "imagen"=> "img/productos/buzo-comfort.webp",
        "precio"=> 14150,
        "publicacion"=> "Agosto, 2023"
    ],
    [
        "id"=> 13,
        "categoria"=> "trending",
        "nombre"=> "CHALECO NUUK",
        "prenda"=> "Chaleco",
        "color"=>"Celeste",
        "talle"=> 1,
        "descripcion"=> "Elevá tu outfit con nuestro chaleco Nuuk. Está hecho de microfibra de poliéster, forrado en tafeta y relleno con guata siliconada. Es matelaseado, con cuello alto y tira cierre con frase. Lleva elástico en la cintura. Es un abrigo ligero, cómodo y creativo para este invierno. ¡Está disponible en color celeste!",
        "imagen"=> "img/productos/chaleco-nuuk.webp",
        "precio"=> 24560,
        "publicacion"=> "Marzo, 2023"
    ],
    [
        "id"=> 17,
        "categoria"=> "trending",
        "nombre"=> "CAMISA MARIA",
        "prenda"=> "Camisa",
        "color"=>"Lila",
        "talle"=> 1,
        "descripcion"=> "Las camisas crop son una tendencia must para esta temporada. La camisa María no puede faltarte. Es de poplín de algodón. Tiene mangas largas. Lleva bolsillo aplicado en delantero y cartera de botones. Está disponible en color lila.",
        "imagen"=> "img/productos/camisa-maria.webp",
        "precio"=> 16390,
        "publicacion"=> "Mayo, 2023"
    ],
    [
        "id"=> 18,
        "categoria"=> "trending",
        "nombre"=> "POLLERA GABI",
        "prenda"=> "Pollera",
        "color"=>"Beige",
        "talle"=> 40,
        "descripcion"=> "La pollera Gabi es de gabardina de algodón. Tiene botones metálicos y pespuntes a contratono. Por su estilo tableado, es la protagonista ideal para un look trendy y canchero. ¡Es una tendencia must para esta temporada!",
        "imagen"=> "img/productos/pollera-gabi.webp",
        "precio"=> 14150,
        "publicacion"=> "Enero, 2023"
    ],
    [
        "id"=> 16,
        "categoria"=> "trending",
        "nombre"=> "REMERA SERENITY",
        "prenda"=> "Remera",
        "color"=>"Beige",
        "talle"=> 2,
        "descripcion"=> "El remerón Serenity es de jersey de algodón. Tiene cuello redondo y mangas cortas. Está disponible en color beige, ¡con una estampa a contratono que es una bomba! La estampa está ubicada en frente y espalda.",
        "imagen"=> "img/productos/remera-serenity.webp",
        "precio"=> 7440,
        "publicacion"=> "Abril, 2023"
    ],
    [
        "id"=> 14,
        "categoria"=> "trending",
        "nombre"=> "REMERA PARIS",
        "prenda"=> "Remera",
        "color"=>"Blanco",
        "talle"=> 40,
        "descripcion"=> "La remera París es una opción súper canchera y rockera para cualquier temporada. Es de jersey de algodón con elastano. Tiene mangas largas, cuello redondo ancho y aberturas para el dedo pulgar. Cuenta con aplique de strass en delantero, que le da toda la onda. Está disponible en color blanco, con costuras a contratono. ¡Combinalo con una pollera y unos borcegos!",
        "imagen"=> "img/productos/remera-paris.webp",
        "precio"=> 8160,
        "publicacion"=> "Septiembre, 2023"
    ],
    [
        "id"=> 15,
        "categoria"=> "trending",
        "nombre"=> "POLLERA COLUCCI",
        "prenda"=> "Pollera",
        "color"=>"Azul",
        "talle"=> 38,
        "descripcion"=> "La pollera Colucci es de denim de algodón con elastano. Es estilo tableada, una de las tendencias principales de esta temporada. ¡Además de súper cómoda y canchera! El tiro llega hasta la cintura.",
        "imagen"=> "img/productos/pollera-colucci.webp",
        "precio"=> 14150,
        "publicacion"=> "Octubre, 2023"
    ],
    [
        "id"=> 19,
        "categoria"=> "verano-2023",
        "nombre"=> "REMERA ADDISON",
        "prenda"=> "Remera",
        "color"=>"Beige",
        "talle"=> 32,
        "descripcion"=> "La remera Addison es el comodín ideal, tanto para el día como la noche. Es de jersey con elastano. Tiene recorte frontal, jaretas y tiras de ajuste. Está disponible en color beige. ¡Combina perfecto con denim!",
        "imagen"=> "img/productos/remera-addison.webp",
        "precio"=> 5630,
        "publicacion"=> "Febrero, 2023"
    ],
    [
        "id"=> 20,
        "categoria"=> "verano-2023",
        "nombre"=> "REMERA MUNA",
        "prenda"=> "Remera",
        "color"=>"Lila",
        "talle"=> 42,
        "descripcion"=> "La remera Polo Muna es de ribb de algodón. Es manga corta, y tiene cuello con chomba y botones a tono. Es una opción fresca y formal para cualquier temporada. ¡Está disponible en el mismo color que nuestra marca, lila!",
        "imagen"=> "img/productos/remera-muna.webp",
        "precio"=> 7440,
        "publicacion"=> "Marzo, 2023"
    ],
    [
        "id"=> 21,
        "categoria"=> "verano-2023",
        "nombre"=> "JUMPER ALMA",
        "prenda"=> "Jumper",
        "color"=>"Marrón",
        "talle"=> 3,
        "descripcion"=> "El jumper Alma es de gabardina de algodón. Tiene breteles anchos y bolsillo en frente. Está disponible en color marrón, con costuras a contratono. ¡Podés combinarlo con cualquiera de nuestras poleras! ",
        "imagen"=> "img/productos/jumper-alma.webp",
        "precio"=> 14150,
        "publicacion"=> "Abril, 2023"
    ],
    [
        "id"=> 22,
        "categoria"=> "verano-2023",
        "nombre"=> "REMERA JACKIE",
        "prenda"=> "Remera",
        "color"=>"Blanco",
        "talle"=> 1,
        "descripcion"=> "El remerón Jackie es de jersey de algodón. Tiene mangas cortas y cuello redondo. Está disponible en color blanco, con estampa en delantero. ¡Llevá las mejores remeras para esta temporada!",
        "imagen"=> "img/productos/remera-jackie.webp",
        "precio"=> 7440,
        "publicacion"=> "Mayo, 2023"
    ],
    [
        "id"=> 23,
        "categoria"=> "verano-2023",
        "nombre"=> "REMERA INDIAN",
        "prenda"=> "Remera",
        "color"=>"Beige",
        "talle"=> 2,
        "descripcion"=> "El remerón Indian es de jersey 100% algodón. Es manga corta y oversized. El color es beige, con estampa. Su cuello es en ribb con material elástico y resistente. ¡El remerón más cómodo y canchero!",
        "imagen"=> "img/productos/remera-indian.webp",
        "precio"=> 6890,
        "publicacion"=> "Junio, 2023"
    ],
    [
        "id"=> 24,
        "categoria"=> "verano-2023",
        "nombre"=> "VESTIDO EMMA",
        "prenda"=> "Vestido",
        "color"=>"Azul",
        "talle"=> 42,
        "descripcion"=> "¿Querés un look canchero y arriesgado? ¡Este vestido es para vos! El vestido Emma es de denim de algodón con elastano. Lleva lavado stone y matizado, para un estilo gastado. Tiene breteles finitos y cierre metálico en el lateral.",
        "imagen"=> "img/productos/vestido-emma.webp",
        "precio"=> 14150,
        "publicacion"=> "Enero, 2023"
    ],
    
];

echo json_encode($productosss);